---
# tasks file for ec2_create
    - name: start an instance with public IP address  
      amazon.aws.ec2_instance:
       name: my-instance.ansible
       instance_type: t2.micro
       security_group: SG:1
       region: ap-south-1
       aws_access_key: "{{aws_access_key}}"
       aws_secret_key: "{{aws_secret_key}}"
       network_interfaces:
        - assign_public_ip: true
       image_id: ami-053b12d3152c0cc71
